name: Code Quality

on:
  push:
    branches: [ main, develop, feature/*, fix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: PHP Code Sniffer (PSR-12)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip
          tools: phpcs

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHP_CodeSniffer
        run: |
          if [ -f "vendor/bin/phpcs" ]; then
            vendor/bin/phpcs --standard=PSR12 src/
          else
            phpcs --standard=PSR12 src/
          fi

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan Static Analysis

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run PHPStan
        continue-on-error: true
        run: |
          if [ -f "vendor/bin/phpstan" ]; then
            vendor/bin/phpstan analyse src/ --level=0 --no-progress || echo "PHPStan has errors - will be fixed incrementally"
          else
            echo "PHPStan not installed, skipping..."
          fi
